In [ ]:
import numpy as np
array=np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12],
                [13,14,15,16]])
#array[start:end:step]
print(array[2:,2:])

In [ ]:
#numpy array is a list pro max
#Numpy = numeric python
#ndarray= n-dimensional array
import numpy as np
np1=np.array([1,0,2,3,4,5,6,7,8,9])
print(np1)

#shape
print(np1.shape)#its like a length of the array

#range
np2=np.arange(10)
print(np2)
 
#step
np3=np.arange(0,10,2)
print(np3)

#zeros
np4=np.zeros(10)
print(np4)

#multidimensional zeros
np5=np.zeros((2,10))
print(np5)

#full
np6=np.full((10),6)
print(np6)

#multidimensional full
np7=np.full((2,10),6)
print(np7)

#convert python lists to np
my_list=[1,2,3,4,5]
np8=np.array(my_list)
print(np8)



In [ ]:
import numpy as np
array=np.array([[['A','B','C'],['D','E','F'],['G','H','I']],
                [['J','K','L'],['M','N','O'],['P','Q','R']],
                [['S','T','U'],['V','W','X'],['Y','Z',' ']]])
print(array.ndim) #number of dimensions
print(array.shape) #shape of the array
word=array[1,2,2]+array[0,0,0]+array[0,1,2]+array[0,2,2]+array[1,0,1]
print(word)

In [ ]:
import numpy as np
#scalar arithmetic
array=np.array([1,2,3])
print(array+1)
print(array-1)
print(array*3)
print(array/2)
print(array**2)
print(array%2)

In [ ]:
import numpy as np
#scalar arithmetic
array1=np.array([1,2,3])
print(array1+1)
print(array1-1)
print(array1*3)
print(array1/2)
print(array1**2)
print(array1%2)
#vectorized math functions
array3=np.array([1.01,2.5,3.99])
print(np.sqrt(array3))
print(np.round(array3))
print(np.pi)
#element-wise arithmetic
array2=np.array([4,5,6])
print(array1+array2)
print(array1-array2)
print(array1*array2)
print(array1/array2)
#comparison operators
print(array1>2)

In [7]:
import numpy as np
array10=np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12],
                 [13,14,15,16]])
array20=np.array([[1,2],[2,3],[3,4],[4,5]])
# print(array10.shape)
# print(array20.shape)
# print(array10*array20)


array1=np.array([[1,2,3,4,5,6,7,8,9,10]])
array2=np.array([[1],[2],[3],[4],[5],[6],[7],[8],[9],[10]])
print(array1.shape)
print(array2.shape)
print(array1*array2)

(1, 10)
(10, 1)
[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


In [9]:
import numpy as np
array=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(np.sum(array))
print(np.mean(array))
print(np.std(array))
print(np.min(array))
print(np.var(array))
print(np.max(array))
print(np.argmin(array))#index of the minimum value
print(np.argmax(array))#index of the maximum value
print(np.sum(array,axis=0))#sum of each column
print(np.sum(array,axis=1))#sum of each row


55
5.5
2.8722813232690143
1
8.25
10
0
9
[ 7  9 11 13 15]
[15 40]


In [ ]:
import numpy as np
ages=np.array([[21,17,19,20,16,30,18,65],
               [39,22,15,99,18,19,20,21]])
teenagers=ages[ages<18] #boolean indexing this flattens the array and returns a 1D array of the values that satisfy the condition if we want to presere the shape we use the where function
adults=ages[(ages>=18) &(ages<65)]
seniors=ages[ages>=65]
evens=ages[ages%2==0]
odds=ages[ages%2!=0]
print(teenagers)
print(adults)
print(seniors)
print(evens)
print(odds)
adults=np.where(ages>=18,ages,0)#this is a better way to do it because it preserves the shape of the array and replaces the values that do not satisfy the condition with 0
print(adults)


[17 16 15]
[21 19 20 30 18 39 22 18 19 20 21]
[65 99]
[20 16 30 18 22 18 20]
[21 17 19 65 39 15 99 19 21]
[[21 -1 19 20 -1 30 18 65]
 [39 22 -1 99 18 19 20 21]]


In [23]:
import numpy as np
rng=np.random.default_rng(seed=1)
print(rng.integers(low=1,high=101,size=3))

[48 52 76]
